name: my_music_ai_demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.2.2
  camera: ^0.11.0
  url_launcher: ^6.2.6
  http: ^1.4.0
  path_provider: ^2.0.11
  path: ^1.8.2
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.4.6 
  google_fonts: ^6.2.1
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/logo_bird.png
    - assets/yellow_button.png
    - assets/green_button.png
    - assets/happy_bird.png
    - assets/note_image.png
    - assets/audio/sample_audio.mp3



flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: false
  fullscreen: true
  
  